FROM blairguk/node-sass-alpine:8.11.0

RUN mkdir /opt/webapp
WORKDIR /opt/webapp
COPY ./package.json .
RUN npm install --production --registry=https://registry.npm.taobao.org
COPY . .

CMD npm run start